name: balena

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: true
      matrix:
        fleet: [g_fokion_sotiropoulos/home]

    steps:
      - uses: actions/checkout@44c2b7a8a4ea60a981eaca3cf939b5f4305c123b # v4
      - uses: balena-io/deploy-to-balena-action@c523907563b2ef5db81cd9519482805f336a630f # v2.0.60
        with:
          balena_token: ${{ secrets.BALENA_API_KEY }}
          fleet: ${{ matrix.fleet }}
          create_tag: true
